# **Parte 1: Creación y manipulación de arrays**

## **Crear un array**
### Crea un array de 10 elementos enteros aleatorios entre 1 y 100. Imprime el array generado.

Para crear un array de 10 elementos con enteros aleatorios entre 1 y 100 hacemos uso de la función _np.random.randint()_ la cual genera números aleatorios en un rango definido. Como tercer parámetro de nuestra función, simplemente establecemos el tamaño que tendrá nuestro arreglo.


In [1]:
!pip install numpy
import numpy as np

array = np.random.randint(1, 101, size=10)
print(array)


[ 1 32 87 97 32 92  2 34  9  2]


## **Reshape**
### A partir del array anterior, convierte este array en una matriz de 2x5.

Nuestro arreglo cuenta ya con 10 elementos. Al utilizar la función _array.reshape()_ que reorganizará los elementos en dos filas y cinco columnas.

In [2]:
matriz = array.reshape(2, 5)
print(matriz)

[[ 1 32 87 97 32]
 [92  2 34  9  2]]


## **Indexación y slicing**
### De la matriz obtenida, extrae la primera fila y la última columna. Imprime ambos resultados por separado.
Para llevar a cabo esta tarea, usaré el slicing.

El primer número de los corchetes indica la o las filas que se quieren extraer de la matriz original.

El segundo número indica la o las columnas que quieren extraerse de la matriz.

Por último, un valor positivo comenzando desde el cero indica un índice de fila o columna a extraer comenzando desde la primera fila o columna. Un valor negativo indica un índice de fila o columna comenzando desde la última fila o columna.

In [3]:
primera_fila = matriz[0, :]
ultima_columna = matriz[:, -1]

print("Primera fila")
print(primera_fila)
print("Última columna")
print(ultima_columna)


Primera fila
[ 1 32 87 97 32]
Última columna
[32  2]


## **Modificación**
### Cambia el valor de los elementos en la segunda fila a ceros.
Para esta tarea usaremos una asignación indicando 1 en el primer valor (la segunda fila) y dos puntos (:) en el segundo valor (todos los elementos de la segunda fila).

In [4]:
matriz[1, :] = 0
print(matriz)

[[ 1 32 87 97 32]
 [ 0  0  0  0  0]]


# **Parte 2: Operaciones básicas con NumPy**
## **Operaciones aritméticas**
### Crea dos arrays de 5 elementos enteros aleatorios entre 1 y 50.
Una vez más creamos dos arreglos utilizando la función _np.random.randint()_.

In [6]:
array1 = np.random.randint(1, 51, size=5)
array2 = np.random.randint(1, 51, size=5)

### Suma ambos arrays y luego multiplícalos entre sí.
Podemos utilizar los operadores matemáticos tal cual o usar funciones para llevar a cabo estas operaciones. En este caso, opté por la primera opción.

In [10]:
suma_arrays = array1 + array2
producto_arrays = array1 * array2

print("Suma")
print(suma_arrays)
print("Multiplicación")
print(producto_arrays)

Suma
[48 57 52 29 29]
Multiplicación
[455 602 667 204 100]


### Calcula el promedio y la desviación estándar de los resultados obtenidos.
Para esto usaremos las funciones _np.mean()_ y _np.std()_.

In [11]:
promedio = np.mean(producto_arrays)
desviacion_estandar = np.std(producto_arrays)

print("Promedio")
print(promedio)
print("Desviación estándar")
print(desviacion_estandar)

Promedio
405.6
Desviación estándar
220.62511189798863


## **Condiciones lógicas**
### Genera un array de 20 números aleatorios entre 0 y 1. Usa condiciones lógicas para


In [12]:
array_logico = np.random.rand(20)

### Reemplazar los valores menores a 0.5 con 0. Reemplazar los valores mayores o iguales a 0.5 con 1.
Podemos cumplir con estos dos requisitos con una única funció n _np.where()_ que es la contracción de un **if**.

In [13]:
array_modificado = np.where(array_logico < 0.5, 0, 1)
print(array_modificado)

[1 1 0 1 0 1 1 1 1 1 0 0 1 1 1 0 1 0 1 1]


## **Producto escalar**
### Crea dos arrays de tamaño 3x3. Calcula el producto escalar entre ambos.
Para esto emplearé la función _np.dot()_

In [16]:
matriz1 = np.random.randint(1, 10, size=(3, 3))
matriz2 = np.random.randint(1, 10, size=(3, 3))

print("Matriz 1")
print(matriz1)
print("Matriz 2")
print(matriz2)

producto_escalar = np.dot(matriz1, matriz2)
print("\nProducto escalar")
print(producto_escalar)

Matriz 1
[[6 2 3]
 [5 8 8]
 [9 9 8]]
Matriz 2
[[4 7 8]
 [2 8 9]
 [1 8 2]]

Producto escalar
[[ 31  82  72]
 [ 44 163 128]
 [ 62 199 169]]


# **Parte 3: Análisis de datos con NumPy**
## **Matriz de datos**
### Crea una matriz de 5 filas y 4 columnas que contenga datos aleatorios entre 1 y 20. Cada fila representa a una persona, y cada columna representa una medición diferente (como altura, peso, edad, presión arterial).

In [17]:
matriz_datos = np.random.randint(1, 21, size=(5, 4))
print(matriz_datos)

[[16 17  8 10]
 [12  9  2 18]
 [ 9  9  9 14]
 [17 17 13  3]
 [ 4 11 16 13]]


## **Estadísticas**
### Calcula la media de cada columna (medición)
La clave de esta tarea se encuentra en la función _np.mean()_. El valor del segundo parámetro _axis=0_ es el que determina que la media se tomará por columna.

In [21]:
media_columnas = np.mean(matriz_datos, axis=0)
print("Media de cada columna")
print(media_columnas)

Media de cada columna
[11.6 12.6  9.6 11.6]


### Encuentra el valor máximo y mínimo de cada fila.
Al igual que el ejercicio anterior, la clave de este ejercicio se encuentra en el uso de _axis_. En este caso aplicado a las funciones _np.max()_ y _np.min()_. El valor _axis=1_ indica que se tomarán los valores mínimo y máximo por fila.

In [20]:
max_filas = np.max(matriz_datos, axis=1)
min_filas = np.min(matriz_datos, axis=1)

print("Máximos por fila")
print(max_filas)
print("Mínimos por fila")
print(min_filas)

Máximos por fila
[17 18 14 17 16]
Mínimos por fila
[8 2 9 3 4]


### Ordena las filas según los valores de la segunda columna (peso).
Para llevar a cabo el paso más complicado de todos necesitamos de _.argsort()_. Al hacer uso de esta función en conjunto de la segunda columna(_matriz_datos[:,1]_) podemos ordenar la matriz de acuerdo al valor en la segunda columna.

In [22]:
matriz_ordenada = matriz_datos[matriz_datos[:, 1].argsort()]
print(matriz_ordenada)

[[12  9  2 18]
 [ 9  9  9 14]
 [ 4 11 16 13]
 [16 17  8 10]
 [17 17 13  3]]
